---
title: "Step 1: Retrieve and Clean Seed Set"
output: html_notebook
---

# Overview

This portion consists of 4 steps:

1.    Retrieve initial records from query
2.    Retrieve abstracts
3.    Extract and clean URLs from abstracts
4.    Find string matches between title and URLs

```{r setup, include=FALSE}
library(dplyr)
library(europepmc)
library(stringr)
```

## 1 Retrieval

The following query string is used in retrieving the initial seed set.

```{r query, echo = FALSE}
my_query <-
  '(((ABSTRACT:"www" OR ABSTRACT:"http" OR ABSTRACT:"https") AND (ABSTRACT:"data" OR ABSTRACT:"resource" OR ABSTRACT:"database"))  NOT (TITLE:"retraction" OR TITLE:"retracted" OR TITLE:"withdrawn" OR TITLE:"withdrawal" OR TITLE:"erratum") NOT ((ABSTRACT:"retract" OR ABSTRACT:"withdraw" ABSTRACT:"erratum" OR ABSTRACT:"github.com" OR ABSTRACT:"github.io" OR ABSTRACT:"cran.r" OR ABSTRACT:"youtube.com" OR ABSTRACT:"bitbucket.org" OR ABSTRACT:"links.lww.com" OR ABSTRACT:"osf.io" OR ABSTRACT:"bioconductor.org" OR ABSTRACT:"annualreviews.org" OR ABSTRACT:"creativecommons.org" OR ABSTRACT:"sourceforge.net" OR ABSTRACT:".pdf" OR ABSTRACT:"clinical trial" OR ABSTRACT:"registry" OR ABSTRACT:"registration" OR ABSTRACT:"trial registration" OR ABSTRACT:"clinicaltrial" OR ABSTRACT:"registration number" OR ABSTRACT:"pre-registration" OR ABSTRACT:"preregistration"))) AND (((SRC:MED OR SRC:PMC OR SRC:AGR OR SRC:CBA))) AND (FIRST_PDATE:[2011 TO 2021])'

my_query
```

```{r retrieve, include=FALSE}
pmc_seed <- epmc_search(query = my_query, limit = 25000)
```

The seed set is filtered to exclude an `NA` rows and publications before 2010.

```{r initial_measures, echo = FALSE}
print(str_glue("Total number of records: {nrow(pmc_seed)}"))

pmc_seed_complete_cases <- filter(pmc_seed,!is.na(pmc_seed$id))
print(str_glue("Number of records: {nrow(pmc_seed_complete_cases)}"))

pmc_seed_filtered <- filter(pmc_seed, pubYear > 2010)
print(str_glue("Number of records after 2010: {nrow(pmc_seed_filtered)}"))

count(pmc_seed, journalTitle)
```

```{r write_seed, echo=FALSE}
today <- str_replace_all(Sys.Date(), "-", "_")
out_file <- paste0("pmc_seed_all_", today, ".csv")

out_path <- file.path("..", "data", "raw", out_file)

write.csv(pmc_seed_filtered, out_path, row.names = FALSE)

print(str_glue("Initial seed saved to {out_path}."))
```



